version: '3.7'
networks:
  acl-apd-net:
    driver: bridge
services:
  test:
    image: ghcr.io/datakaveri/acl-apd-test:latest
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/configs/5.5.0/apd-config-test.json:/usr/share/app/secrets/all-verticles-configs/5.5.0/config-dev.json
      - /home/ubuntu/configs/5.5.0/keystore-file.jks:/usr/share/app/secrets/keystore-file.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./example-configs/5.5.0/:/usr/share/app/example-configs
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
      - $PWD:$PWD -w $PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ./iudx-pmd-ruleset.xml:/usr/share/app/iudx-pmd-ruleset.xml
      - ./google_checks.xml:/usr/share/app/google_checks.xml
    command: bash -c "docker/runTests.sh"
    network_mode: host

  integTest:
    image: ghcr.io/datakaveri/acl-apd-depl:latest
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/configs/5.5.0/apd-config-dev.json:/usr/share/app/secrets/configs/5.5.0/config.json
      - /home/ubuntu/configs/5.5.0/keystore-file.jks:/usr/share/app/secrets/keystore-file.jks
    command: bash -c "exec java $$FS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c secrets/configs/5.5.0/config.json"
    ports:
      - "8080:8080"
    networks:
      - acl-apd-net
    depends_on:
      - "zookeeper"

  zookeeper:
    image: zookeeper:latest
    expose:
      - "2181"
    networks:
      - acl-apd-net
